In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('mobile.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1019 entries, 0 to 1018
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Name            1019 non-null   object 
 1   Spec Score      1019 non-null   int64  
 2   rating          1019 non-null   float64
 3   price           1019 non-null   int64  
 4   img             1019 non-null   object 
 5   tag             1019 non-null   object 
 6   sim             1019 non-null   object 
 7   processor       993 non-null    object 
 8   storage         999 non-null    object 
 9   battery         1013 non-null   object 
 10  display         1018 non-null   object 
 11  camera          1008 non-null   object 
 12  memoryExternal  668 non-null    object 
 13  version         971 non-null    object 
 14  fm              294 non-null    object 
dtypes: float64(1), int64(2), object(12)
memory usage: 119.5+ KB


In [4]:
df.head()

Name  Spec Score  rating  price  \
0  OPPO Reno 14 Pro 5G          89    4.65  41990   
1      OPPO Reno 14 5G          87    4.75  32990   
2           Poco F7 5G          83    4.75  31999   
3         Vivo X200 FE          89    4.65  49990   
4         OPPO K13x 5G          73    4.20  11999   

                                                 img       tag  \
0  https://cdn1.smartprix.com/rx-is822PXo3-w280-h...  UPCOMING   
1  https://cdn1.smartprix.com/rx-iRGgfcGDH-w280-h...  UPCOMING   
2  https://cdn1.smartprix.com/rx-icmgBU9Q2-w280-h...  LAUNCHED   
3  https://cdn1.smartprix.com/rx-iHI7IaQgQ-w280-h...  UPCOMING   
4  https://cdn1.smartprix.com/rx-iXUulomIY-w280-h...  LAUNCHED   

                                                 sim  \
0  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
1  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
2  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
3  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...   
4                 Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi   

                                           processor  \
0      Dimensity 8450, Octa Core, 3.25 GHz Processor   
1      Dimensity 8350, Octa Core, 3.35 GHz Processor   
2   Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor   
3  Dimensity 9300 Plus, Octa Core, 3.25 GHz Proce...   
4       Dimensity 6300, Octa Core, 2.4 GHz Processor   

                     storage                                  battery  \
0  12 GB RAM, 256 GB inbuilt  6200 mAh Battery with 80W Fast Charging   
1   8 GB RAM, 256 GB inbuilt  6000 mAh Battery with 80W Fast Charging   
2  12 GB RAM, 256 GB inbuilt  7550 mAh Battery with 90W Fast Charging   
3  12 GB RAM, 256 GB inbuilt  6500 mAh Battery with 90W Fast Charging   
4   4 GB RAM, 128 GB inbuilt  6000 mAh Battery with 45W Fast Charging   

                                             display  \
0  6.83 inches, 1272 x 2800 px, 120 Hz Display wi...   
1  6.59 inches, 1256 x 2760 px, 120 Hz Display wi...   
2  6.83 inches, 1280 x 2772 px, 120 Hz Display wi...   
3  6.31 inches, 1216 x 2640 px, 120 Hz Display wi...   
4  6.67 inches, 720 x 1604 px, 120 Hz Display wit...   

                                              camera  \
0  50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...   
1  50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...   
2        50 MP + 8 MP Dual Rear & 20 MP Front Camera   
3  50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...   
4         50 MP + 2 MP Dual Rear & 8 MP Front Camera   

                     memoryExternal      version           fm  
0                               NaN  Android v15  No FM Radio  
1                               NaN  Android v15  No FM Radio  
2         Memory Card Not Supported  Android v15          NaN  
3         Memory Card Not Supported  Android v15          NaN  
4  Memory Card Supported, upto 2 TB  Android v15          NaN

In [5]:
df.duplicated().sum()

2

In [6]:
print(df[df.duplicated()])

                      Name  Spec Score  rating  price  \
393          Oppo Reno 14F          84     4.0  34990   
719  Samsung Galaxy M37 5G          75     4.4  17990   

                                                   img       tag  \
393  https://cdn1.smartprix.com/rx-iTvelPVTP-w280-h...  UPCOMING   
719  https://cdn1.smartprix.com/rx-i2WUf3VQ1-w280-h...   RUMORED   

                                         sim  \
393  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   
719  Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC   

                                           processor  \
393  Snapdragon 6 Gen1, Octa Core, 2.2 GHz Processor   
719                              Octa Core Processor   

                      storage                                  battery  \
393  8 GB RAM, 256 GB inbuilt  6000 mAh Battery with 45W Fast Charging   
719  8 GB RAM, 128 GB inbuilt  6500 mAh Battery with 45W Fast Charging   

                                               display  \
393  6.57 inches, 1080 x 237

In [7]:
df.isnull().sum()

Name                0
Spec Score          0
rating              0
price               0
img                 0
tag                 0
sim                 0
processor          26
storage            20
battery             6
display             1
camera             11
memoryExternal    351
version            48
fm                725
dtype: int64

In [8]:
del df['img']

SIM card

In [9]:
df['sim'].unique()

array(['Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Blaster',
       'Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi',
       'Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster',
       'Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC, IR Blaster',
       'Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC',
       'Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC',
       'Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi',
       'Dual Sim, 3G, 4G, VoLTE, Wi-Fi',
       'Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster',
       'Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC',
       'Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster',
       'Dual Sim, 3G, 4G, Wi-Fi', 'Dual Sim, 3G, 4G, Wi-Fi, NFC',
       'Dual Sim, 3G, 4G, 5G, Wi-Fi, NFC',
       'No Sim Supported, Wi-Fi, IR Blaster', 'Dual Sim, 3G, Wi-Fi',
       'Single Sim, 3G, 4G, VoLTE', 'Dual Sim',
       'Single Sim, 4G, VoLTE, Wi-Fi', 'Dual Sim, 3G, 4G, VoLTE',
       'Single Sim, 4G, VoLTE',
       'Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster',
       'Dual Sim, 3G, 4G',

In [10]:
data = df.copy()

In [11]:
data['sup_3G'] = [1 if '3G' in x else 0 for x in data['sim']]
data['sup_4G'] = [1 if '4G' in x else 0 for x in data['sim']]
data['sup_5G'] = [1 if '5G' in x else 0 for x in data['sim']]
data['nfc'] = [1 if 'NFC' in x else 0 for x in data['sim']]

In [12]:
del data['sim']

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1019 entries, 0 to 1018
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Name            1019 non-null   object 
 1   Spec Score      1019 non-null   int64  
 2   rating          1019 non-null   float64
 3   price           1019 non-null   int64  
 4   tag             1019 non-null   object 
 5   processor       993 non-null    object 
 6   storage         999 non-null    object 
 7   battery         1013 non-null   object 
 8   display         1018 non-null   object 
 9   camera          1008 non-null   object 
 10  memoryExternal  668 non-null    object 
 11  version         971 non-null    object 
 12  fm              294 non-null    object 
 13  sup_3G          1019 non-null   int64  
 14  sup_4G          1019 non-null   int64  
 15  sup_5G          1019 non-null   int64  
 16  nfc             1019 non-null   int64  
dtypes: float64(1), int64(6), object(1

Processor

In [14]:
data['processor'].unique()[0:10]

array(['Dimensity 8450, Octa Core, 3.25\u2009GHz Processor',
       'Dimensity 8350, Octa Core, 3.35\u2009GHz Processor',
       'Snapdragon 8s Gen4, Octa Core, 3.2\u2009GHz Processor',
       'Dimensity 9300 Plus, Octa Core, 3.25\u2009GHz Processor',
       'Dimensity 6300, Octa Core, 2.4\u2009GHz Processor',
       'Dimensity 7300, Octa Core, 2.5\u2009GHz Processor',
       'Dimensity 9300 Plus, Octa Core, 3.4\u2009GHz Processor',
       'Exynos 1380, Octa Core, 2.4\u2009GHz Processor',
       'Dimensity 8350 Extreme, Octa Core, 3.35\u2009GHz Processor',
       'Dimensity 7400, Octa Core, 2.6\u2009GHz Processor'], dtype=object)

In [15]:
import re 

In [16]:
data['proc_name'] = data['processor'].str.extract(r'(\w+)', flags=re.IGNORECASE)

In [17]:
data['proc_name'].unique()

array(['Dimensity', 'Snapdragon', 'Exynos', 'Octa', 'Helio', 'Unisoc',
       'Kirin', 'Bionic', 'Tensor', 'Apple', nan, 'Xring', 'Google',
       'Single', 'Tiger', '512', '1', 'Quad', 'AMD', 'Dimensit',
       'Spreadtrum', 'A13'], dtype=object)

In [18]:
data['proc_GHz'] = [
    x.replace(' ', '').split(',')[-1] if isinstance(x, str) and '\u2009' in x else None
    for x in data['processor']
]
data['proc_GHz'] = data['proc_GHz'].str.partition('\u2009')[0].astype('float')
#data['proc_GHz'] = pd.to_numeric(data['proc_GHz'], errors='coerce', downcast='float')
data.loc[data['processor'].str.contains('MHz', na=False), 'proc_GHz'] /= 1000

In [19]:
data['proc_GHz'].unique()

array([3.25e+00, 3.35e+00, 3.20e+00, 2.40e+00, 2.50e+00, 3.40e+00,
       2.60e+00, 4.32e+00,      nan, 3.11e+00, 2.30e+00, 2.80e+00,
       2.00e+00, 3.00e+00, 1.80e+00, 2.63e+00, 3.30e+00, 2.20e+00,
       2.96e+00, 2.70e+00, 4.04e+00, 3.46e+00, 2.90e+00, 3.10e+00,
       4.05e+00, 4.47e+00, 3.63e+00, 3.22e+00, 3.36e+00, 1.30e+00,
       1.60e+00, 3.05e+00, 3.78e+00, 3.39e+00, 2.91e+00, 2.84e+00,
       3.73e+00, 3.90e+00, 2.85e+00, 2.36e+00, 5.00e+02, 1.00e+00,
       1.10e+00, 2.08e-01, 2.05e+00, 5.12e-01, 1.00e-03, 1.40e+00,
       2.65e+00, 2.10e+00, 1.40e-03])

In [20]:
del data['processor']

Storage

In [21]:
data['storage'][0:10]

0    12 GB RAM, 256 GB inbuilt
1     8 GB RAM, 256 GB inbuilt
2    12 GB RAM, 256 GB inbuilt
3    12 GB RAM, 256 GB inbuilt
4     4 GB RAM, 128 GB inbuilt
5     8 GB RAM, 128 GB inbuilt
6    12 GB RAM, 256 GB inbuilt
7     4 GB RAM, 128 GB inbuilt
8    12 GB RAM, 256 GB inbuilt
9     6 GB RAM, 128 GB inbuilt
Name: storage, dtype: object

In [22]:
data['ram'] = data['storage'].str.extract(r'(\d+\u2009\w+ RAM)', flags=re.IGNORECASE)
data['ram'] = [
    float(x.split('\u2009')[0]) / 1024 if isinstance(x, str) and 'MB' in x else 
    float(x.split('\u2009')[0]) if isinstance(x, str) else None 
    for x in data['ram']
]

In [23]:
data['ram'].unique()

array([12. ,  8. ,  4. ,  6. , 16. ,  nan, 24. ,  3. ,  0.5,  2. ,  1. ])

In [24]:
data['rom'] = data['storage'].str.extract(r'(\d+\u2009\w+ inbuilt)', flags=re.IGNORECASE)
data['rom'] = [
    float(x.split('\u2009')[0]) * 1024 if isinstance(x, str) and 'TB' in x else 
    float(x.split('\u2009')[0]) if isinstance(x, str) else None 
    for x in data['rom']
]

In [25]:
data['rom'].unique()

array([ 256.,  128.,  512.,   64., 1024.,    4.,   32.,   nan,   16.,
         12.,    8.])

Battery

In [26]:
data['battery'][0:10]

0    6200 mAh Battery with 80W Fast Charging
1    6000 mAh Battery with 80W Fast Charging
2    7550 mAh Battery with 90W Fast Charging
3    6500 mAh Battery with 90W Fast Charging
4    6000 mAh Battery with 45W Fast Charging
5    5500 mAh Battery with 90W Fast Charging
6    7550 mAh Battery with 90W Fast Charging
7    6000 mAh Battery with 15W Fast Charging
8    6500 mAh Battery with 90W Fast Charging
9    5000 mAh Battery with 25W Fast Charging
Name: battery, dtype: object

In [27]:
data['bat_size'] = data['battery'].str.extract(r'(\d+)\u2009\w+', flags=re.IGNORECASE).astype('float')
#data['bat_size'] = pd.to_numeric(data['bat_size'], errors='coerce', downcast='integer')

data['bat_size'].unique()

array([ 6200.,  6000.,  7550.,  6500.,  5500.,  5000.,  5850.,  5150.,
        7300.,  4700.,  7100.,  7000., 10000.,  5200.,  4800.,  5160.,
        6550.,  7500.,  4500.,  5110.,  6260.,  4000.,  6400.,  5700.,
        3561.,  5600.,  5030.,  3349.,  4600.,  4685.,  5100.,  4310.,
        4900.,  3240.,  5800.,  4005.,  4400.,  5410.,  6700.,  5400.,
        5003.,  3582.,  3000.,  5240.,  7200.,  6600.,    nan,  4190.,
        5300.,  4492.,  4383.,  3900.,  1450.,  3279.,  6100.,  4674.,
        7620.,  3274.,  5050.,  8000., 25500.,  7700.,  1800.,  4970.,
        5630.,  6720.,  5910.,  4385.,  1325.,  4415.,  7800.,  5230.,
        2500.,  5060.,  4610.,  1100.,   800.,  2000.,  7410.,  4441.,
        4575.,  4820.,  4355.,  1500.,  1000.,  6520.,  6800.,  6150.,
        4830.,  3700.,  6300., 10100.,  6880.,  6415., 28000.,  7050.,
        4325.,  2800.,  1200.,  5180.,  8680.,  4805.,  4650.,   950.,
        1900.,  5750.,  4020.,  4410.,  3500.,  4250.,  1150.,  3110.,
      

Display

In [28]:
data['display'].unique()

array(['6.83 inches, 1272\u2009x\u20092800\u2009px, 120 Hz Display with Punch Hole',
       '6.59 inches, 1256\u2009x\u20092760\u2009px, 120 Hz Display with Punch Hole',
       '6.83 inches, 1280\u2009x\u20092772\u2009px, 120 Hz Display with Punch Hole',
       '6.31 inches, 1216\u2009x\u20092640\u2009px, 120 Hz Display with Punch Hole',
       '6.67 inches, 720\u2009x\u20091604\u2009px, 120 Hz Display with Punch Hole',
       '6.77 inches, 1080\u2009x\u20092392\u2009px, 120 Hz Display with Punch Hole',
       '6.74 inches, 720\u2009x\u20091600\u2009px, 90 Hz Display with Water Drop Notch',
       '6.74 inches, 1080\u2009x\u20092340\u2009px, 120 Hz Display with Punch Hole',
       '6.67 inches, 1260\u2009x\u20092800\u2009px, 120 Hz Display with Punch Hole',
       '6.7 inches, 1220\u2009x\u20092712\u2009px, 120 Hz Display with Punch Hole',
       '6.72 inches, 1080\u2009x\u20092408\u2009px, 120 Hz Display with Punch Hole',
       '6.32 inches, 1216\u2009x\u20092640\u2009px, 120 Hz Disp

Inches

In [29]:
data['inches'] = data['display'].str.extract(r'(\d+\.?\d*)').astype('float')

display size

In [30]:
data['disp_size'] = data['display'].str.extract(r'(\d+\.?\d*\u2009\w+\u2009\d+)')

In [31]:
data['disp_size'] = [
    int(x.split('\u2009')[0]) * int(x.split('\u2009')[-1]) if isinstance(x, str) else None
    for x in data['disp_size']
]

display hz

In [32]:
data['disp_hz'] = data['display'].str.extract(r'(\d+\.?\d*) Hz').astype('float')

In [33]:
data['disp_hz'].unique()

array([120.,  90., 144.,  nan, 165., 185.])

In [34]:
del data['display']
del data['storage']
del data['battery']

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1019 entries, 0 to 1018
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Name            1019 non-null   object 
 1   Spec Score      1019 non-null   int64  
 2   rating          1019 non-null   float64
 3   price           1019 non-null   int64  
 4   tag             1019 non-null   object 
 5   camera          1008 non-null   object 
 6   memoryExternal  668 non-null    object 
 7   version         971 non-null    object 
 8   fm              294 non-null    object 
 9   sup_3G          1019 non-null   int64  
 10  sup_4G          1019 non-null   int64  
 11  sup_5G          1019 non-null   int64  
 12  nfc             1019 non-null   int64  
 13  proc_name       993 non-null    object 
 14  proc_GHz        863 non-null    float64
 15  ram             994 non-null    float64
 16  rom             999 non-null    float64
 17  bat_size        1013 non-null   f

Camera

In [35]:
data['camera'].unique()

array(['50\u2009MP + 50\u2009MP + 50\u2009MP Triple Rear & 50\u2009MP Front Camera',
       '50\u2009MP + 50\u2009MP + 8\u2009MP Triple Rear & 50\u2009MP Front Camera',
       '50\u2009MP + 8\u2009MP Dual Rear & 20\u2009MP Front Camera',
       '50\u2009MP + 2\u2009MP Dual Rear & 8\u2009MP Front Camera',
       '50\u2009MP + 2\u2009MP Dual Rear & 32\u2009MP Front Camera',
       '50\u2009MP + 2\u2009MP Dual Rear & 5\u2009MP Front Camera',
       '50\u2009MP + 8\u2009MP + 2\u2009MP Triple Rear & 13\u2009MP Front Camera',
       '50\u2009MP + 50\u2009MP + 8\u2009MP Triple Rear & 32\u2009MP Front Camera',
       '50\u2009MP + 50\u2009MP + 10\u2009MP Triple Rear & 50\u2009MP Front Camera',
       '50\u2009MP + 50\u2009MP Dual Rear & 32\u2009MP Front Camera',
       '50\u2009MP + 8\u2009MP Dual Rear & 32\u2009MP Front Camera',
       '50\u2009MP + 50\u2009MP + 50\u2009MP Triple Rear & 32\u2009MP Front Camera',
       '50\u2009MP + 12\u2009MP + 8\u2009MP Triple Rear & 10\u2009MP Front Camera

In [36]:
camera = data['camera'].str.partition('&', expand=True)

In [37]:
camera

0  1                    2
0     50 MP + 50 MP + 50 MP Triple Rear   &   50 MP Front Camera
1      50 MP + 50 MP + 8 MP Triple Rear   &   50 MP Front Camera
2                50 MP + 8 MP Dual Rear   &   20 MP Front Camera
3      50 MP + 50 MP + 8 MP Triple Rear   &   50 MP Front Camera
4                50 MP + 2 MP Dual Rear   &    8 MP Front Camera
...                                  ... ..                  ...
1014             50 MP + 8 MP Dual Rear   &   16 MP Front Camera
1015            50 MP + 50 MP Dual Rear   &   32 MP Front Camera
1016  50 MP + 12 MP + 10 MP Triple Rear   &   12 MP Front Camera
1017    50 MP + 5 MP + 2 MP Triple Rear   &   13 MP Front Camera
1018                    48 MP Dual Rear   &    8 MP Front Camera

[1019 rows x 3 columns]

In [38]:
camera[2].unique()

array([' 50\u2009MP Front Camera', ' 20\u2009MP Front Camera',
       ' 8\u2009MP Front Camera', ' 32\u2009MP Front Camera',
       ' 5\u2009MP Front Camera', ' 13\u2009MP Front Camera',
       ' 10\u2009MP Front Camera', ' 16\u2009MP Front Camera',
       ' 12\u2009MP Front Camera',
       ' 32\u2009MP + 32\u2009MP Dual Front Camera',
       ' 10\u2009MP + 4\u2009MP Dual Front Camera',
       ' 11.1\u2009MP Front Camera', ' 24\u2009MP Front Camera',
       ' 60\u2009MP Front Camera',
       ' 50\u2009MP + 2\u2009MP Dual Front Camera',
       ' 20\u2009MP + 20\u2009MP Dual Front Camera',
       ' 40\u2009MP Front Camera', ' 42\u2009MP Front Camera', '',
       ' 10.5\u2009MP Front Camera', ' 48\u2009MP Front Camera',
       ' 0.3\u2009MP Front Camera', ' 10.8\u2009MP Front Camera', nan,
       ' 8\u2009MP + 8\u2009MP Dual Front Camera', ' Main Front Camera',
       ' 12\u2009MP + 4\u2009MP Dual Front Camera',
       ' 24\u2009MP + 24\u2009MP Dual Front Camera',
       ' 20\u2009MP + 2\

In [39]:
def rear_search(line):
    line = str(line)
    if 'Dual' in line:
        return 2
    elif 'Triple' in line:
        return 3
    return 1

camera[1] = camera[0].apply(rear_search)
camera[2] = camera[2].str.extract(r'(\d+)\s*MP', flags=re.IGNORECASE).astype(float)
camera[0] = camera[0].str.extract(r'(\d+)\s*MP', flags=re.IGNORECASE).astype(float)

In [40]:
data['camera'] = camera[0]
data['front_camera'] = camera[2]
data['camera_amount'] = camera[1]

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1019 entries, 0 to 1018
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Name            1019 non-null   object 
 1   Spec Score      1019 non-null   int64  
 2   rating          1019 non-null   float64
 3   price           1019 non-null   int64  
 4   tag             1019 non-null   object 
 5   camera          1008 non-null   float64
 6   memoryExternal  668 non-null    object 
 7   version         971 non-null    object 
 8   fm              294 non-null    object 
 9   sup_3G          1019 non-null   int64  
 10  sup_4G          1019 non-null   int64  
 11  sup_5G          1019 non-null   int64  
 12  nfc             1019 non-null   int64  
 13  proc_name       993 non-null    object 
 14  proc_GHz        863 non-null    float64
 15  ram             994 non-null    float64
 16  rom             999 non-null    float64
 17  bat_size        1013 non-null   f

External memory

In [42]:
data['memoryExternal'].unique()

array([nan, 'Memory Card Not Supported',
       'Memory Card Supported, upto 2\u2009TB', 'Memory Card (Hybrid)',
       'Memory Card (Hybrid), upto 1\u2009TB',
       'Memory Card Supported, upto 1\u2009TB',
       'Memory Card (Hybrid), upto 2\u2009TB',
       'Memory Card (Hybrid), upto 1.5\u2009TB',
       'Memory Card Supported, upto 512\u2009GB', 'Memory Card Supported',
       'Memory Card Supported, upto 32\u2009GB',
       'Memory Card Supported, upto 256\u2009GB',
       'Memory Card Supported, upto 1000\u2009GB',
       'Memory Card (Hybrid), upto 1.02\u2009TB',
       'Memory Card Supported, upto 128\u2009GB',
       'Memory Card Supported, upto 64\u2009GB',
       'Memory Card Supported, upto 16\u2009GB',
       'Memory Card (Hybrid), upto 512\u2009GB',
       'Memory Card Supported, upto 48\u2009GB',
       'Memory Card (Hybrid), upto 8\u2009GB'], dtype=object)

In [43]:
ext_memory = data['memoryExternal'].str.split('\u2009', expand=True)
ext_memory[2] = ext_memory[0].str.extract(r'(\d+)', flags=re.IGNORECASE).astype('float')
ext_memory.loc[ext_memory[1] == 'TB', 2] *= 1024
ext_memory[2] = ext_memory[2].round(2)
ext_memory[2].unique()

array([  nan, 2048., 1024.,  512.,   32.,  256., 1000.,  128.,   64.,
         16.,   48.,    8.])

In [44]:
# Fixing the TypeError by checking for None instead of float in the list comprehension

data['ext_memory'] = ext_memory[2]
data['is_ext_memory'] = [
    0 if isinstance(x, str) and 'Not' in x 
    else (None if x is None else 1) 
    for x in data['memoryExternal']
]

del data['memoryExternal']

data.is_ext_memory.value_counts()

is_ext_memory
1    796
0    223
Name: count, dtype: int64

Creator

In [45]:
data['creator'] = data['Name'].str.extract(r'(\w+)')
del data['Name']
data['creator'].unique()

array(['OPPO', 'Poco', 'Vivo', 'Xiaomi', 'Samsung', 'Motorola', 'OnePlus',
       'Nothing', 'iQOO', 'Realme', 'Oppo', 'Lava', 'Tecno', 'Infinix',
       'Huawei', 'Apple', 'CMF', 'Oneplus', 'AI', 'Tesla', 'Google',
       'Honor', 'POCO', 'Sony', 'itel', 'Nokia', 'Nubia', 'HMD',
       'Ulefone', 'Light', 'BlackZone', 'Namotel', 'Fairphone', 'Asus',
       'Jio', 'Unihertz', 'Acer', 'Redmi', 'Trump', 'Vertu', 'iKall',
       'Doogee', 'Energizer', 'Bluefox', 'Gamma', 'Snexian', 'HTC', 'TCL',
       'Oscal', 'Sharp', 'Alcatel', 'Moondrop', 'Meizu'], dtype=object)

In [46]:
del data['tag']
del data['version']
del data['fm']
del data['proc_name']

In [47]:
data.round({'proc_GHz': 2, 'inches': 2})
data.head()

Spec Score  rating  price  camera  sup_3G  sup_4G  sup_5G  nfc  proc_GHz  \
0          89    4.65  41990    50.0       1       1       1    1      3.25   
1          87    4.75  32990    50.0       1       1       1    1      3.35   
2          83    4.75  31999    50.0       1       1       1    1      3.20   
3          89    4.65  49990    50.0       1       1       1    1      3.25   
4          73    4.20  11999    50.0       1       1       1    0      2.40   

    ram    rom  bat_size  inches  disp_size  disp_hz  front_camera  \
0  12.0  256.0    6200.0    6.83  3561600.0    120.0          50.0   
1   8.0  256.0    6000.0    6.59  3466560.0    120.0          50.0   
2  12.0  256.0    7550.0    6.83  3548160.0    120.0          20.0   
3  12.0  256.0    6500.0    6.31  3210240.0    120.0          50.0   
4   4.0  128.0    6000.0    6.67  1154880.0    120.0           8.0   

   camera_amount  ext_memory  is_ext_memory creator  
0              3         NaN              1    OPPO  
1              3         NaN              1    OPPO  
2              2         NaN              0    Poco  
3              3         NaN              0    Vivo  
4              2      2048.0              1    OPPO

In [48]:
data.isnull().sum()

Spec Score         0
rating             0
price              0
camera            11
sup_3G             0
sup_4G             0
sup_5G             0
nfc                0
proc_GHz         156
ram               25
rom               20
bat_size           6
inches             1
disp_size          5
disp_hz           98
front_camera      32
camera_amount      0
ext_memory       658
is_ext_memory      0
creator            0
dtype: int64

In [49]:
data['inches'].unique()

array([ 6.83,  6.59,  6.31,  6.67,  6.77,  6.74,  6.7 ,  6.72,  6.32,
        6.78,  6.8 ,  6.75,  6.57,  6.4 ,  6.82,  6.6 ,  6.9 ,  6.88,
        6.5 ,  6.71,  6.2 ,  6.1 ,  6.84,  6.79,  6.55,  6.73,  8.2 ,
        6.3 ,  6.68,  6.36,  8.03, 10.2 ,  2.7 ,  6.45,  6.85,  7.6 ,
        7.95,  6.95,  3.92,  8.8 ,  8.  ,  4.  ,  2.8 ,  4.5 ,  6.81,
        1.8 ,  1.77,  7.  ,   nan,  2.4 ,  8.12,  6.56,  2.  ,  6.43,
        7.76,  6.58,  6.44,  5.  ,  3.  ,  5.56,  8.1 ,  7.82,  7.85,
        6.38,  6.28,  6.91,  6.14,  5.42,  6.39,  4.7 ,  7.1 ,  6.61,
        6.65])

In [50]:
data['inches'] = data['inches'].astype('float')

In [51]:
data.dropna(subset=['bat_size', 'inches', 'disp_size', 'camera'], inplace=True)

In [52]:
data.loc[data['creator'] == 'Oppo', 'creator'] = 'OPPO'

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 998 entries, 0 to 1018
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Spec Score     998 non-null    int64  
 1   rating         998 non-null    float64
 2   price          998 non-null    int64  
 3   camera         998 non-null    float64
 4   sup_3G         998 non-null    int64  
 5   sup_4G         998 non-null    int64  
 6   sup_5G         998 non-null    int64  
 7   nfc            998 non-null    int64  
 8   proc_GHz       855 non-null    float64
 9   ram            985 non-null    float64
 10  rom            988 non-null    float64
 11  bat_size       998 non-null    float64
 12  inches         998 non-null    float64
 13  disp_size      998 non-null    float64
 14  disp_hz        915 non-null    float64
 15  front_camera   978 non-null    float64
 16  camera_amount  998 non-null    int64  
 17  ext_memory     353 non-null    float64
 18  is_ext_memory 

In [54]:
line = ['disp_size', 'ext_memory', 'creator']
for x in line:
    data[x] = data[x].astype('category')

In [55]:
data.to_csv('mobile_clean.csv', index=False)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=2511581e-5c9d-4885-bce2-6cc92ed25703' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>